{
	"count": 50100,
	"results": [
    {
		"listing_id": 711491162,
		"state": "active",
		"user_id": 163911063,
		"category_id": 69188195,
		"title": "Candy Corn Inspired Curly Que Hair Ties, Halloween Hair Ties",
		"description": "Candy Corn is a popular American and Canadian candy found around Halloween. The colors for this hair tie are inspired by this candy. \n\nThe base of this cute ponytail holder is a no-damage ponytail elastic - with no metal parts, there&#39;s nothing to catch or pull your hair.  Just pop the elastic around your ponytail as many times as necessary and the curly ques will sit atop it, adding some fun to a simple hairstyle.",
		"creation_tsz": 1564541210,
		"ending_tsz": 1575172010,
		"original_creation_tsz": 1564541210,
		"last_modified_tsz": 1564541211,
		"price": "5.00",
		"currency_code": "CAD",
		"quantity": 5,
		"sku": [],
		"tags": ["hair bands", "hair elastics", "hair ties", "ponytail holders", "gift for girls", "halloween accessory", "candy corn hair tie", "cute hair ties", "fall hair accessory", "halloween lover gift", "hair accessories", "trick or treat cutie", "curly que hair tie"],
		"category_path": ["Accessories", "Hair", "Scrunchie"],
		"category_path_ids": [69150467, 69153737, 69188195],
		"materials": ["yarn", "elastic hair ties"],
		"shop_section_id": 26769967,
		"featured_rank": null,
		"state_tsz": 1564541210,
		"url": "https:\/\/www.etsy.com\/listing\/711491162\/candy-corn-inspired-curly-que-hair-ties?utm_source=wiivvetsy&utm_medium=api&utm_campaign=api",
		"views": 0,
		"num_favorers": 0,
		"shipping_template_id": null,
		"processing_min": 1,
		"processing_max": 3,
		"who_made": "i_did",
		"is_supply": "false",
		"when_made": "2010_2019",
		"item_weight": "25",
		"item_weight_unit": "g",
		"item_length": "100",
		"item_width": "80",
		"item_height": "20",
		"item_dimensions_unit": "mm",
		"is_private": false,
		"recipient": null,
		"occasion": null,
		"style": null,
		"non_taxable": false,
		"is_customizable": false,
		"is_digital": false,
		"file_data": "",
		"should_auto_renew": false,
		"language": "en-US",
		"has_variations": false,
		"taxonomy_id": 226,
		"taxonomy_path": ["Accessories", "Hair Accessories", "Ties & Elastics"],
		"used_manufacturer": false
	}
		],
	"params": {
		"limit": 25,
		"offset": 0,
		"page": null,
		"keywords": null,
		"sort_on": "created",
		"sort_order": "down",
		"min_price": null,
		"max_price": null,
		"color": null,
		"color_accuracy": 0,
		"tags": null,
		"category": null,
		"location": null,
		"lat": null,
		"lon": null,
		"region": null,
		"geo_level": "city",
		"accepts_gift_cards": "false",
		"translate_keywords": "false"
	},
	"type": "Listing",
	"pagination": {
		"effective_limit": 25,
		"effective_offset": 0,
		"next_offset": 25,
		"effective_page": 1,
		"next_page": 2
	}
}